Controller
But-Better/CalcApi pull request #5
Opened 2021-11-03 18:02 UTC by Ktechen

- Added GET-Request for VAT calculation.
- Added Tests case for this GET-Request.

2021-11-03 18:27 UTC, notefox requested changes
wenn du noch den weiteren Test schreibst, würde ich es durchwinken

2021-11-03 22:21 UTC, MathisHTW commented
**We should merge Notefoxes PR before tackling this one because of all the dependencies!!!**

2021-11-04 07:02 UTC, notefox requested changes
Der Pull Request geht auf den falschen Branch
Müsste auf stage gehen, geht aber auf master(live)

2021-11-04 09:06 UTC, Ktechen commented
wrong branch

2021-11-04 09:06 UTC, closed without merging